#LINK IO Stellar toml
FEDERATION_SERVER = 'https://api.linkupio.com/federation'
AUTH_SERVER = 'https://api.linkupio.com/auth'
TRANSFER_SERVER = 'https://api.linkupio.com/transfer'
WEB_AUTH_ENDPOINT = 'https://api.linkupio.com/web_auth'
DIRECT_PAYMENT_SERVER = 'https://api.linkupio.com/sep31/direct'
VERSION = '1.0.0'
#
SIGNING_KEY = 'GCQLPBWOQ5PAJYEEQBE7GDSY7X3LCYKFEBKOCNF3OUA6F74ORK74HVSQ'
ACCOUNTS = ['GCQLPBWOQ5PAJYEEQBE7GDSY7X3LCYKFEBKOCNF3OUA6F74ORK74HVSQ', 'GASBV6W7GGED66MXEVC7YZHTWWYMSVYEY35USF2HJZBLABLYIFQGXZY6']
#OUR_VALIDATORS = 'GCQLPBWOQ5PAJYEEQBE7GDSY7X3LCYKFEBKOCNF3OUA6F74ORK74HVSQ'
#ASSET_VALIDATOR = 'GCQLPBWOQ5PAJYEEQBE7GDSY7X3LCYKFEBKOCNF3OUA6F74ORK74HVSQ'
#
[DOCUMENTATION]
ORG_NAME='LINK.IO Ltd.'
ORG_DBA='LINK'
ORG_URL='https://www.linkupio.com'
ORG_LOGO='https://linkupio.com/ngnc-logo.png'
ORG_DESCRIPTION='LINK is a Global Cross Border payments platform for the next billion 2225666i6y11py Cross, London, United Kingdom, WC1X 0ND '
#ORG_PHYSICAL_ADDRESS_ATTESTATION='https://www.linkupio.com/address_attestation.jpg' E.g. a utility bill, mail from a financial institution, or business license
ORG_PHONE_NUMBER='+905338570073'
#ORG_PHONE_NUMBER_ATTESTATION='https://www.linkupio.com/phone_attestation.jpg'
#ORG_KEYBASE='linkio'
ORG_TWITTER='link_io'
ORG_GITHUB='linkio'
ORG_OFFICIAL_EMAIL='support@linkupio.com'
ORG_SUPPORT_EMAIL='support@linkupio.com'
#
[[PRINCIPALS]]
name='Evarist Emmanuel'
email='engremmanuelec@gmail.com'
keybase='ebuka'
telegram='evaristec'
twitter='ecevarist'
github='ebuka'
#id_photo_hash='**'
#verification_photo_hash='**'
#
[[VALIDATORS]]
ALIAS = 'linkio'
DISPLAY_NAME='LINK'
HOST='**'
PUBLIC_KEY='GCQLPBWOQ5PAJYEEQBE7GDSY7X3LCYKFEBKOCNF3OUA6F74ORK74HVSQ'

[[CURRENCIES]]
code = 'NGNC'
issuer = 'GCQLPBWOQ5PAJYEEQBE7GDSY7X3LCYKFEBKOCNF3OUA6F74ORK74HVSQ'
status = 'live'
display_decimals = 2
name = 'Naira Coin'
desc = 'Asset backed token pegged 1:1 to Nigerian Naira ₦'
conditions = 'Redeemable via the LINK  (www.linkio.africa) platform. Withdrawal fees apply'
image='https://linkupio.com/ngnc-logo.png'
is_unlimited = true
is_asset_anchored = true
anchor_asset_type = 'fiat'
#
anchor_asset = 'NGN'
redemption_instructions = 'To deposit and withdraw NGNC ensure you're signed up on LINK (www.linkio.africa)'
info_server = '**'
#
# Federation Format:
#        Forwarding supported by sending to: linkio.africa
#           type=forward
#           forward_type=bank_account
#           bank_code=<nibss 6 digit code of receiving bank>
#           nuban=<recipient 10 digit nuban account number at receiving bank>
#
# Example: https://api.cowrie.exchange/federation?type=forward&forward_type=bank_account&bank_code=[000000]&nuban=[0000000000]
#
# Minimum Amount Forward: ₦25,000
# Maximum Amount Forward: ₦4,000,000
#        Forwarding Fees: ₦200
#
# Bank Codes
#        AccessBank: 000014
#          CitiBank: 000009
#       DiamondBank: 000005
#           Ecobank: 000010
#    EnterpriseBank: 000019
#              FCMB: 000003
#      FidelityBank: 000007
#         FirstBank: 000016
#            GTBank: 000013
#          Heritage: 000020
#      KeystoneBank: 000002
#          SkyeBank: 000008
#           Stanbic: 000012
# StandardChartered: 000021
#      SterlingBank: 000001
#               UBA: 000004
#         UnionBank: 000018
#         UnityBank: 000011
#          WemaBank: 000017
#        ZenithBank: 000015